config/routes.rb
Rails.application.routes.draw do
  get "payments/create"
  devise_for :users

  root "products#home"
  get "/home", to: "products#home", as: "home_user"
  get "/all_products", to: "products#all_products", as: "all_products"
  get "/record", to: "products#record", as: "record"

  resources :users do
    resources :addresses
  end

  resources :categories, param: "category_name"
  resources :products, param: "code"
  resources :stores
  resources :orders

  resources :stores do
    resources :products, param: "code"
  end

  resources :categories do
    resources :products, param: "code"
  end

  resources :products, param: "code" do
    resources :reviews
  end

  get "/cart", to: "carts#show", as: "cart"
  delete "carts/:id", to: "carts#destroy"
  post "/carts/add_to_cart", to: "carts#add_to_cart", as: "add_to_cart"
  delete "/carts/remove_from_cart/:id", to: "carts#remove_from_cart", as: "remove_from_cart"
  get "carts/empty_cart", to: "carts#empty_cart", as: "empty_cart"
  patch "carts/update_cart/:id", to: "carts#update_cart", as: "update_cart"
  get "/error", to: "carts#error", as: "error"

  post "line_items/:id/add", to: "line_items#add_quantity", as: "line_item_add"
  post "line_items/:id/reduce", to: "line_items#reduce_quantity", as: "line_item_reduce"
  post "line_items", to: "line_items#create"
  get "line_items/:id", to: "line_items#show", as: "line_item"
  delete "line_items/:id", to: "line_items#destroy"


  get "/checkout", to: "carts#checkout", as: "checkout"
  post "/place_order", to: "carts#place_order", as: "place_order"
  # post '/payments/create', to: 'payments#create', as: ""
  get "/thank_you", to: "orders#thank_you"

  namespace :admin do
    resources :users
    resources :products, param: "code"
    resources :stores
    resources :categories, param: "category_name"
    resources :orders

    resources :stores do
      resources :products, param: "code"
    end

    resources :categories do
      resources :products, param: "code"
    end
  end

  get "/admin/dashboard", to: "admin/users#dashboard", as: "admin_dashboard"
end

app/models/store.rb
class Store < ApplicationRecord
  mount_uploader :logo, ImageUploader
  has_many :products, dependent: :destroy

  validates :store_name, uniqueness: {message: "already exists"}
  validates :description, presence: {message: " needs to be filled"}
end

app/controllers/admin/stores_controller.rb
class Admin::StoresController < ApplicationController
  before_action :check_user_permission
  before_action :set_store, only: %i[show edit update destroy]

  def index
    if current_user.store_admin?
      @stores = Store.where(id: current_user.store_id)
    elsif current_user.super_admin? || current_user.staff?
      @stores = Store.all
    end
  end

  def show
    @store = Store.find(params[:id])
    @products = @store.products
  end

  def new
    @store = Store.new
  end

  def edit
    @store = Store.find(params[:id])
  end

  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to admin_stores_path, notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @store = Store.find(params[:id])
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to admin_stores_path, notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @store.destroy
    redirect_to admin_stores_path, notice: "Store destroyed successfully"
  end

  private

  def set_store
    @store = Store.find(params[:id])
  end

  def store_params
    params.permit(:store_name, :description, :logo)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[show edit update destroy]
  # before_action :check_user_permission

  def index
    @stores = Store.all
  end

  def show
    @store = Store.find(params[:id])
    @products = @store.products
  end

  private

  def set_store
    @store = Store.find(params[:id])
  end

  def store_params
    params.require(:store).permit(:store_name, :description, :logo)
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/admin/stores/edit.html.erb
<h2 class=text-center>Edit store details</h2>
<div class="row py-2">
 <div class= "col-lg-4 mx-auto">
  <%= form_with url: admin_store_path(@store.id), method: :patch do |form| %>
    <% if @store.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

        <ul>
          <% @store.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <div class="field mt-3">
    <%= form.label :store_name, style: "display: block" %>
    <%= form.text_field :store_name, value: @store.store_name, class:"form-control py-2"  %>
  </div>

  <div class="field mt-3">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, value: @store.description, class:"form-control py-2"  %>
  </div>

  <div class="field mt-3">
    <%= form.label :logo %>
    <%= form.file_field :logo,  class:"form-control py-2"  %>
  </div>

  <div>
    <%= form.submit "Update Changes", data: {turbo:false}, class:"form-control py-2 btn btn-dark fw-bold shadow"%>
  </div>
<% end %>

app/views/admin/stores/index.html.erb
<div class="result">
<div><h1>Stores</h1></div>
  <div>
    <% if current_user.super_admin? %>
      <%= link_to "Create Stores",new_admin_store_path, class:"btn btn-dark"%>
    <% end %>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Store name</th>
      <th>Description</th>
      <th>Actions </th>
    </tr>
  </thead>
  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.store_name %></td>
        <td><%= store.description %></td>
        
        <td style="display:flex; flex-direction:row;">
          <%= link_to "Show", admin_store_path(store.id), class: "btn btn-success" %>
          <%= link_to "Edit", edit_admin_store_path(store.id), class: "btn btn-primary" %>
          <%= link_to "Delete",admin_store_path(store.id), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                }, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>



app/views/admin/stores/new.html.erb
<h1 class="text-center">New store</h1>

<div class="row py-2">
 <div class= "col-lg-4 mx-auto">
<%= form_with url: admin_stores_path do |form| %>
  <% if @store.errors.any? %>
    <div style="color: red">
      <ul>
        <% @store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mt-3">
    <%= form.label :store_name do%>
    Store name<span class="required" style="color:red;">*</span>
    <% end %><br />
    <%= form.text_field :store_name, autofocus: true, autocomplete: "name", :required =>true, class:"form-control py-2" %>
  </div>

  <div class="field mt-3">
    <%= form.label :description do %>
    Description<span class="required" style="color:red;">*</span>
    <% end %><br />
    <%= form.text_field :description, autofocus: true, autocomplete: "name",:required =>true, class:"form-control py-2" %>
  </div>

  <div class="field mt-3">
    <%= form.label :logo %>
    <%= form.file_field :logo,  class:"form-control py-2"  %>
  </div>

  <div class="actions mt-4 mb-5">
    <%= form.submit  "Create", data: {turbo:false}, class:"form-control py-2 btn btn-dark fw-bold shadow"  %>
  </div>
<% end %>


<div>
  <%= link_to "Back to stores", admin_stores_path %>
</div>



app/views/admin/stores/show.html.erb
<div class="text-center">
  <h2><%= image_tag @store.logo.url, width:180 %></h2>
   <%= link_to "Show products summary", admin_store_products_path(@store) %>
</div>



<div class="row" style="margin-bottom:80px;">
  <% @products.each do |product|%>
      <div class="col-md-4" onclick="show(this)">

        <div class="product-box" id="product-box">
            <%=image_tag product.image.url, class:"product-index" if product.image?%>
              <ul>
                    <strong class="product-name"><%= product.product_name%></strong><br>by <strong><%= product.store.store_name%></strong><br>
                        Rs.<%= product.price%><br>
                        <span>&#11088;</span><%= product.rating%><br>
                    
                        <%= link_to "", admin_product_path(code: product.code)%>
              </ul>
        </div>
      </div>
  <%end%>
</div>

<%= javascript_include_tag "show"%>
