config/routes.rb
Rails.application.routes.draw do
  get "payments/create"
  devise_for :users

  root "products#home"
  get "/home", to: "products#home", as: "home_user"
  get "/all_products", to: "products#all_products", as: "all_products"
  get "/record", to: "products#record", as: "record"

  resources :users do
    resources :addresses
  end

  resources :categories, param: "category_name"
  resources :products, param: "code"
  resources :stores
  resources :orders

  resources :stores do
    resources :products, param: "code"
  end

  resources :categories do
    resources :products, param: "code"
  end

  resources :products, param: "code" do
    resources :reviews
  end

  get "/cart", to: "carts#show", as: "cart"
  delete "carts/:id", to: "carts#destroy"
  post "/carts/add_to_cart", to: "carts#add_to_cart", as: "add_to_cart"
  delete "/carts/remove_from_cart/:id", to: "carts#remove_from_cart", as: "remove_from_cart"
  get "carts/empty_cart", to: "carts#empty_cart", as: "empty_cart"
  patch "carts/update_cart/:id", to: "carts#update_cart", as: "update_cart"
  get "/error", to: "carts#error", as: "error"

  post "line_items/:id/add", to: "line_items#add_quantity", as: "line_item_add"
  post "line_items/:id/reduce", to: "line_items#reduce_quantity", as: "line_item_reduce"
  post "line_items", to: "line_items#create"
  get "line_items/:id", to: "line_items#show", as: "line_item"
  delete "line_items/:id", to: "line_items#destroy"


  get "/checkout", to: "carts#checkout", as: "checkout"
  post "/place_order", to: "carts#place_order", as: "place_order"
  # post '/payments/create', to: 'payments#create', as: ""
  get "/thank_you", to: "orders#thank_you"

  namespace :admin do
    resources :users
    resources :products, param: "code"
    resources :stores
    resources :categories, param: "category_name"
    resources :orders

    resources :stores do
      resources :products, param: "code"
    end

    resources :categories do
      resources :products, param: "code"
    end
  end

  get "/admin/dashboard", to: "admin/users#dashboard", as: "admin_dashboard"
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[show destroy add_to_cart remove_from_cart empty_cart update_cart place_order checkout]

  def show
    @cart = current_order
  end

  def add_to_cart
    @product = Product.find(params[:product_id])
    @line_item = @order.line_items.find_by(product_id: params[:product_id])
    if @line_item
      @line_item.quantity = @line_item.quantity + params[:quantity].to_i
      @line_item.save
    else
      @order.line_items.create(product_id: params[:product_id], quantity: params[:quantity], price: @product.discounted_price || @product.price)
    end
    @order.save
    flash[:notice] = "Added to cart"
    redirect_to cart_path
  end

  def remove_from_cart
    @line_item = @order.line_items.find(params[:id])
    if @line_item.destroy
      @order.save
      flash[:notice] = "Removed from cart"
      redirect_to cart_path
    end
  end

  def update_cart
    @line_item = @order.line_items.find(params[:id])
    @line_item.quantity = params[:quantity]
    if @line_item.save
      @order.save
      flash[:notice] = "Updated Line Item"
    end
    redirect_to cart_path
  end

  def empty_cart
    @order.destroy if @order.id == session[:order_id]
    session[:order_id] = nil
    flash[:notice] = "Cart is cleared"
    redirect_to cart_path
  end

  def error
    render layout: "simple_layout", template: "carts/error"
  end

  def checkout
  end

  def place_order
    binding.pry
    @payment = Payment.new(card_number: params[:card_number], cvv: params[:cvv], expiry_date: "#{params["expiry_date(1i)"]}/#{params["expiry_date(2i)"]}", order_id: @order.id)
    @order.address_id = params[:delivery_address]
    if @order.save
      @order.update(status: "placed")
      flash[:notice] = "Order Placed Successfully"
      redirect_to @order
    end
  end

  private

  def set_cart
    @order = current_order
  end

  def set_product
    @product = Product.find(params[:product_id])
  end

  def set_line_item
    @line_item = LineItem.find(params[:line_item_id])
  end

  def cart_params
    params.require(:cart).permit(:user_id)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>">
  <p>
    <strong>User:</strong>
    <%= cart.user_id %>
  </p>

</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/checkout.html.erb
<% if @order.total_price > 1.0 %>
  <strong class="mr-10">Payable Amount:  Rs.<%= @order.total_price%> </strong>
  <%= form_tag place_order_path, method: :post do %>
    <script
      src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>"
      data-amount="<%= @order.total_price %>"
      data-email="<%= current_user.email %>"
      data-currency="usd">
    </script>
  <% end %>
<% else %>
  <h2><%= render plain: "Cart is empty, add products to place order!" %></h2>
<% end %>






<% if @order.total_price > 1.0 %>
  <div class="row py-2">
  <div class= "col-lg-4 mx-auto">
    <h2>Billing details</h2>

    <strong class="mr-10">Payable Amount:  Rs.<%= @order.total_price%> </strong>

    
    <%= form_with url: place_order_path do |f|%>
      <% if @order.errors.any? %>
        <div style="color: red">
          <ul>k
            <% @order.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.label :delivery_address do %>
      Delivery address<span class="required" style="color:red;">*</span>
      <% end %><br />
      <%= select_tag :delivery_address, options_from_collection_for_select(Address.where(user_id: current_user.id), "id", "area"), :required =>true %><br>

      <div class="">
          <%= link_to "Add new address", new_user_address_path(user_id: current_user.id), class: "btn btn-success" %><br><br>
      </div>

      <%= f.label :card_number do %>
      Card Number<span class="required" style="color:red;">*</span>
      <% end %><br />
      <%= f.text_field :card_number, :required =>true, class:"form-control py-2" %><br>

      <%= f.label :cvv do %>
      CVV <span class="required" style="color:red;">*</span>
      <% end %><br />
      <%= f.text_field :cvv, pattern: '[0-9]{3}', :required =>true, class:"form-control py-2" %><br>

      <%= f.label :expiry_date, 'Expiration Date (YYYY/MM)' do %>
      Expiration Date<span class="required" style="color:red;">*</span>
      <% end %><br />
      <%= f.date_select :expiry_date, :discard_day => true, :start_year => Date.today.year, :end_year => (Date.today.year+10), :use_month_numbers => true, class:"form-control py-2" %>  
      
      <%= f.submit "Proceed and Place Order",class:"form-control py-2 btn btn-dark fw-bold shadow" %>
    
    <% end %>

  </div>
  </div>
<% else %>
  <h2><%= render plain: "Cart is empty, add products to place order!" %></h2>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Show this cart", @cart %> |
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/error.html.erb
<div class="containerx">
    <h2>404</h2>
    <h3>Oops, nothing here...</h3>
    <p>Please Check the URL</p>
    <p>Otherwise, <a href="http://localhost:3000/home">Click here</a> to redirect to homepage.</p>
</div>
<style>
 @import url('https://fonts.googleapis.com/css2?family=Merriweather:wght@900&display=swap');

        body{
            font-family: 'Merriweather', serif;
            margin: 0;
            background-color: #9cc3d5;
            text-align: center;
            color: white;
            user-select: none;
            padding-top: 18vh;
        }
        .containerx{
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 100%;
            background-color: #5ca3dd93;
        }
        h2{
            font-size: 150px;
            margin: 0;
            text-shadow: 15px 5px 2px black;
        }
        h3{
            font-size: 40px;
            margin: 20px;
        }
        p{
            font-size: 18px;
            margin: 5px;
        }
        p:last-of-type{
            margin-bottom: 35px;
        }
        a{
            text-decoration: none;
            
        }

</style>

app/views/carts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Carts</h1>

<div id="carts">
  <% @carts.each do |cart| %>
    <%= render cart %>
    <p>
      <%= link_to "Show this cart", cart %>
    </p>
  <% end %>
</div>

<%= link_to "New cart", new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/show.html.erb
<% if @cart.line_items.present?%>
  <ul>
      <div class="container">
        <div class="row">
          <div class="col-12">
          <table class="table table-image">
            <thead>
              <tr>
                <th scope="col"></th>
                <th scope="col">Quantity</th>
                <th scope="col">Product</th>
                <th scope="col">Unit Price</th>
                <th scope="col">Line Total </th>
                <th scope="col">  </th>
              </tr>
            </thead>
            <tbody>
              <% @cart.line_items.each do |item| %>
                <tr>
                  <td><%= image_tag item.product.image.url, class: "cart-product" %><br>
                      <% unless item.product.rating %>
                        <%= render plain: "-Be the first to review-" %>
                      <% else %>
                        <span>&#11088;</span><%=item.product.rating %>
                      <% end %>
                    </td>
                    <td>
                      <%= button_tag "-", type: 'button', onclick: "decrement(this, #{item.id})", class: 'btn btn-default'%>
                      <%= number_field_tag "line_quantity_#{item.id}", item.quantity, {style: "width:40px", onblur: "set_quantity(this, #{item.id})"}%>
                      <%= button_tag "+", type: 'button', onclick: "increment(this, #{item.id})", class: 'btn btn-default'%><br>
                    </td>
                  <td><%= item.product.product_name %></td>
                  <td>Rs.<%= item.product.price  %></td>
                  <td><strong>Rs.<%= item.total_price %></strong><br>

                  <% if item.product.discount%>
                   <%= content_tag :p, item.product.price * item.quantity, style: "text-decoration: line-through;color: gray;" %>
                  <% end %>
                  </td>
                  <td>
                    <%= button_to "Remove", remove_from_cart_path(item.id), method: :delete %>
                    <%= button_to "Update", update_cart_path(item.id), method: :patch, :id => "update_#{item.id}", params: { "quantity": item.quantity }%>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>  
          </div>
        </div>
      </div>
  </ul>
  <div style="display:flex; flex-direction:row;  justify-content: space-between">
    <div><%= link_to "Continue Shopping", all_products_path, class:"btn btn-success" %></div>
    <div style="display:flex; flex-direction:row; align-items:center">
      <strong class="mr-10">Total:  Rs.<%=@order.total_price  %> </strong>
      <%= link_to 'Clear Cart', empty_cart_path, class: "btn btn-success mr-30" %>
      <%# <a><%= button_to "Update Cart", add_to_cart_path, method: :post, class: "btn btn-success mr-30" %>
    </div>
  </div>
  <div class="total-price mt-20">
    <%= link_to "Checkout", checkout_path, class: "btn btn-success" %>
  </div>
  <br><br><br><br>

<% else %>  
  <%= render plain: "Your cart is empty "%><%= link_to "Continue Shopping", all_products_path , class: "btn btn-success"%><br>
<% end %>

<script>
  function increment(ele, id) {
    quantity = ele.previousElementSibling;
    quantity.stepUp();
    update = document.getElementById("update_" + id);
    update.parentElement.lastChild.value = quantity.value;
  }

  function decrement(ele, id) {
    // debugger;
    var quantity = ele.nextElementSibling;
    if (quantity.value > 1) {
      quantity.stepDown();
    }
    update = document.getElementById("update_" + id);
    update.parentElement.lastChild.value = quantity.value;
  }

  function set_quantity(ele, id) {
    // debugger;
    update = document.getElementById("update_" + id);
    update.parentElement.lastChild.value = ele.value;
  }
</script>
