config/routes.rb
Rails.application.routes.draw do
  get "payments/create"
  devise_for :users

  root "products#home"
  get "/home", to: "products#home", as: "home_user"
  get "/all_products", to: "products#all_products", as: "all_products"
  get "/record", to: "products#record", as: "record"

  resources :users do
    resources :addresses
  end

  resources :categories, param: "category_name"
  resources :products, param: "code"
  resources :stores
  resources :orders

  resources :stores do
    resources :products, param: "code"
  end

  resources :categories do
    resources :products, param: "code"
  end

  resources :products, param: "code" do
    resources :reviews
  end

  get "/cart", to: "carts#show", as: "cart"
  delete "carts/:id", to: "carts#destroy"
  post "/carts/add_to_cart", to: "carts#add_to_cart", as: "add_to_cart"
  delete "/carts/remove_from_cart/:id", to: "carts#remove_from_cart", as: "remove_from_cart"
  get "carts/empty_cart", to: "carts#empty_cart", as: "empty_cart"
  patch "carts/update_cart/:id", to: "carts#update_cart", as: "update_cart"
  get "/error", to: "carts#error", as: "error"

  post "line_items/:id/add", to: "line_items#add_quantity", as: "line_item_add"
  post "line_items/:id/reduce", to: "line_items#reduce_quantity", as: "line_item_reduce"
  post "line_items", to: "line_items#create"
  get "line_items/:id", to: "line_items#show", as: "line_item"
  delete "line_items/:id", to: "line_items#destroy"


  get "/checkout", to: "carts#checkout", as: "checkout"
  post "/place_order", to: "carts#place_order", as: "place_order"
  # post '/payments/create', to: 'payments#create', as: ""
  get "/thank_you", to: "orders#thank_you"

  namespace :admin do
    resources :users
    resources :products, param: "code"
    resources :stores
    resources :categories, param: "category_name"
    resources :orders

    resources :stores do
      resources :products, param: "code"
    end

    resources :categories do
      resources :products, param: "code"
    end
  end

  get "/admin/dashboard", to: "admin/users#dashboard", as: "admin_dashboard"
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items
  has_many :orders, through: :line_items
  has_many :reviews, dependent: :destroy, autosave: true

  belongs_to :category
  belongs_to :store

  mount_uploader :image, ImageUploader

  validates :product_name, presence: true
  validates :description, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :image, allow_blank: false, format: {
    with: %r{\.(gif|jpg|png)\Z}i,
    message: "must be a URL for GIF, JPG or PNG image."
  }
  validates :code, numericality: {only_integer: true}, presence: true, uniqueness: true, length: {is: 5, message: "Assign unique product code with 5 digits"}

  def to_param
    code
  end

  def discounted_price
    if discount
      price - (price * (discount.to_f / 100))
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:all_products, :record, :home, :show]
  before_action :set_product, only: %i[show update destroy]
  before_action :check_user_permission

  def home
    render template: "home"
  end

  def index
    @products = Product.all
    if params[:store_id]
      @products = Store.find(params[:store_id]).products
    end
    if current_user.store_admin?
      @products = Store.find(current_user.store_id).products
    end
    if params[:category_id]
      @category = Category.find(params[:category_id])
      @products = @products.where(category_id: @category.id)
    end
  end

  def show
    @store = Store.find(params[:store_id]) if params[:store_id]
    @category = Category.find(category_name: params[:category_name]) if params[:category_name]
    @product = Product.find_by(code: params[:code])
  end

  def record
    @products = Product.order(rating: :desc).paginate(page: 1, per_page: 5)
    render template: "record"
  end

  def new
    @product = Product.new
    @stores = Store.all
    @stores = Store.where(id: current_user.store_id) if current_user.store_admin?
  end

  def edit
    @product = Product.find_by(code: params[:code])
  end

  def create
    @product = Product.new(product_name: params[:product_name], price: params[:price], description: params[:description], discount: params[:discount], image: params[:image], rating: params[:rating], code: params[:code], store_id: params[:store_id], category_id: params[:category_id])
    # @product.rating = 0
    if @product.save
      redirect_to admin_products_path, notice: "Added a product successfully"
    else
      render action: "new"
    end
  end

  def update
    @product = Product.find_by(code: params[:code])
    if @product.update(product_params)
      redirect_to admin_products_path, notice: "Updated product successfully"
    else
      render action: "edit"
    end
  end

  def destroy
    @product.destroy
    redirect_to admin_products_path, notice: "Product destroyed successfully"
  end

  private

  def set_product
    @product = Product.find_by(code: params[:code])
  end

  def set_store
    @store = Store.find(params[:store_id])
  end

  def set_category
    @category = Category.find(params[:category_id])
  end

  def product_params
    params.permit(:product_name, :price, :description, :discount, :image, :rating, :code, :store_id, :category_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:all_products, :record, :home, :show]
  before_action :set_product, only: %i[show update destroy]

  def home
    render template: "home"
  end

  def index
    @products = Product.all
    @products = @products.paginate(page: params[:page], per_page: params[:per_page])
  end

  def all_products
    @products = Product.all
    @per_page = params[:per_page] if params[:per_page]
    @sort_price = params[:sort_price] if params[:sort_price]
    @products = @products.paginate(page: params[:page], per_page: params[:per_page])
    if @sort_price == "Price - low to high"
      @products = Product.order(price: :asc).paginate(page: params[:page], per_page: params[:per_page])
    elsif @sort_price == "Price - high to low"
      @products = Product.order(price: :desc).paginate(page: params[:page], per_page: params[:per_page])
    elsif @sort_price == "Relevance"
      @products = Product.paginate(page: params[:page], per_page: params[:per_page])
    elsif @sort_price == "Highest rating"
      @products = Product.order(rating: :desc).paginate(page: params[:page], per_page: params[:per_page])
    end

    @category_id = params[:category_id] if params[:category_id] && params[:category_id].present?
    @products = @products.where(category_id: @category_id) if @category_id
  end

  def show
    @store = Store.find(params[:store_id]) if params[:store_id]
    @product = Product.find_by(code: params[:code])
  end

  def record
    @products = Product.order(rating: :desc).paginate(page: 1, per_page: 5)
    render template: "record"
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:code])
  end

  def create
    @product = Product.create(product_name: params[:product_name], price: params[:price], description: params[:description], discount: params[:discount], visibility: params[:visibility], rating: params[:rating], image: params[:image], code: params[:code])
    if @product.save
      redirect_to products_path
    end
  end

  def update
    @product = Product.find(params[:code])
    @product.update(product_params)
    redirect_to products_path
  end

  def destroy
    @product = Product.find(params[:code])
    @product.destroy
    redirect_to products_path
  end

  private

  def set_product
    @product = Product.find_by(code: params[:code])
  end

  def set_store
    @store = Store.find(params[:store_id])
  end

  def set_category
    @category = Category.find(params[:category_id])
  end

  def product_params
    params.require(:product).permit(:product_name, :price, :description, :discount, :visibility, :image, :rating, :code, :store_id, :category_id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb

<h2 class=text-center>Edit product details</h2>
<div class="row py-2">
 <div class= "col-lg-4 mx-auto">
    <%= form_with url: admin_product_path(code: @product.code), method: :patch do |form| %>
      <% if @product.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
            <% @product.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

    
      <div class="field mt-3">
        <%= form.label :product_name, style: "display: block" %>
        <%= form.text_field :product_name ,value: @product.product_name,autofocus: true, autocomplete: "product_name", :required =>true, class:"form-control py-2"  %>
      </div>
 
      <div class="field mt-3">
        <%= form.label :description, style: "display: block" %>
        <%= form.text_area :description,value: @product.description, autofocus: true, autocomplete: "description", :required =>true, class:"form-control py-2"  %>
      </div>

      <div class="field mt-3">
        <%= form.label :price, style: "display: block" %>
        <%= form.number_field :price ,value: @product.price, autofocus: true, autocomplete: "price", :required =>true, class:"form-control py-2" %>
      </div>

      <div class="field mt-3">
        <%= form.label :category, style: "display: block"  %>
        <%= select_tag "category_id", options_from_collection_for_select(Category.all, "id", "category_name", :selected => @product.category_id), autofocus: true, autocomplete: "category", :required =>true, class:"form-control py-2"  %>
      </div>
      <div class="field mt-3">
        <%= form.label :store, style: "display: block"  %>
        <%= select_tag "store_id", options_from_collection_for_select(Store.all, "id", "store_name", :selected => @product.store_id), autofocus: true, autocomplete: "store", :required =>true, class:"form-control py-2"  %>
      </div>

      <div class="field mt-3">
        <%= form.label :code, style: "display:block"%>
        <%= form.number_field :code,value: @product.code, autofocus: true, autocomplete: "code", :required =>true, class:"form-control py-2"  %>
      </div>

      <div class="field mt-3">
        <%= form.label :discount, style: "display: block" %>
        <%= form.number_field :discount,value: @product.discount, autofocus: true, autocomplete: "discount", :required =>true, class:"form-control py-2"  %>
      </div>

      <div class="field mt-3">
        <%= form.label :visibility, style: "display: block" %>
        <%= form.check_box :visibility, checked: @product.visibility %>
      </div>
    
      <div class="field mt-3">
        <%= form.label :image, style: "display: block" %>
        <%= form.file_field :image,value: @product.image, autofocus: true, class:"form-control py-2"  %>
        <!--
        <% if @product.image %>
          <%= form.check_box :remove_image%>
        Remove image
        <%end%>
        -->
      </div>

      <% if @product.image.present?%>
        <div>
          <%= image_tag @product.image.url ,style:"height:190px; width:150px;" %>
        </div>
      <% end %>
  
      <div class="actions mt-4 mb-5" >
        <%= form.submit "Update", data: {turbo:false}, class:"form-control py-2 btn btn-dark fw-bold shadow"%>
      </div>
    <% end %>
</div>

<div>
  <%= link_to "Back to products", admin_products_path %>
</div>

app/views/admin/products/index.html.erb
<div class="result">
<div><h1>Products</h1></div>
<div><%= link_to "Create Products",new_admin_product_path, class:"btn btn-dark"%></div>
</div>


<table class="table">
<thead>
  <tr>
    <th>Product Code</th>              
    <th>Product</th>                      
    <th>Price </th>
    <th>Rating</th>
    <th>Discount</th>
    <th>Discounted Price</th>
    <th>Actions</th>
  </tr>
</thead>
<tbody>
 <% @products.each do |product| %>
  <tr>
    <td><%= product.code%></td>
    <td><%= product.product_name%></td>         
    <td>Rs.<%=product.price %></td> 
    <td><% unless product.rating %>
        <%= render plain: "-"%>
        <% else %>
        <span>&#11088;</span><%=product.rating %>
        <% end %>
    </td> 
    <td><%=product.discount %>%</td>
    <td>Rs.<%=product.discounted_price %></td>
    <td style="display:flex; flex-direction:row;">
      <%= link_to "Show", admin_product_path(code: product.code), class: "btn btn-success" %>
      <%= link_to "Edit", edit_admin_product_path(code: product.code), class: "btn btn-primary" %>
      <%= link_to "Delete",admin_product_path(code: product.code), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                }, class: "btn btn-danger" %>
    </td>   
  </tr>
  <% end %>
  </tbody>
 </table>

app/views/admin/products/new.html.erb
<h1 class="text-center">New Product</h1>
<div class="text-center">
  <%= link_to "Back to products", admin_products_path %>
</div>
<div class="row py-2">
 <div class= "col-lg-4 mx-auto">
    <%= form_with url: admin_products_path do |form| %>
      <% if @product.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
            <% @product.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

    
      <div class="field mt-3">
        <%= form.label :product_name do %>
        Product name<span class="required" style="color:red;">*</span>
        <% end %><br />
        <%= form.text_field :product_name , autofocus: true, autocomplete: "product_name", :required =>true, class:"form-control py-2"  %>
      </div>
 
      <div class="field mt-3">
        <%= form.label :description %>
        <%= form.text_area :description, autofocus: true, autocomplete: "description", :required =>true, class:"form-control py-2"  %>
      </div>

      <div class="field mt-3">
        <%= form.label :price do %>
          Price <span class="required" style="color:red;">*</span>
        <% end %><br />
        <%= form.number_field :price , autofocus: true, autocomplete: "price", :required =>true, class:"form-control py-2" %>
      </div>

      <div class="field mt-3">
        <%= form.label :category do  %>
        Category<span class="required" style="color:red;">*</span>
        <% end %><br />
        <%= select_tag "category_id", options_from_collection_for_select(Category.all, "id", "category_name"), autofocus: true, autocomplete: "category", :required =>true, class:"form-control py-2"  %>
      </div>

      <div class="field mt-3">
        <%= form.label :store do %>
        Store<span class="required" style="color:red;">*</span>
        <% end %><br />
        <%= select_tag "store_id", options_from_collection_for_select(@stores || Store.all, "id", "store_name"), autofocus: true, autocomplete: "store", :required =>true, class:"form-control py-2"  %>
      </div>

      <div class="field mt-3">
        <%= form.label :code do%>
        Product Code<span class="required" style="color:red;">*</span>
        <% end %><br />
        <%= form.number_field :code, autofocus: true, autocomplete: "code", :required =>true, class:"form-control py-2"  %>
      </div>

      <div class="field mt-3">
        <%= form.label :discount %>
        <%= form.number_field :discount, autofocus: true, autocomplete: "discount", class:"form-control py-2"  %>
      </div>
    
      <div class="field mt-3">
        <%= form.label :image do%>
        Image<span class="required" style="color:red;">*</span>
        <% end %><br />
        <%= form.file_field :image, autofocus: true, :required =>true, class:"form-control py-2"  %>
   
      </div>
  
      <div class="actions mt-4 mb-5" >
        <%= form.submit "Create", data: {turbo:false}, class:"form-control py-2 btn btn-dark fw-bold shadow"%>
      </div>
    <% end %>
</div>
</div>
</div>

app/views/admin/products/show.html.erb
<div class="mybox">
      <div class="leftx">
        <% if @product.image?%>
          <%= image_tag @product.image.url, class:"product-show"%>
          <%else %>
          <%= render plain: "OK" %>
        <% end %>
      </div>

      <div class="rightx" >
        <ul>
          <strong><%= @product.product_name%></strong><br>by <strong><%= @product.store.store_name%></strong><br>
          Rs.<%= @product.price%><br>
          <%= @product.description%><br>
          <strong><%= @product.category.category_name%>'s Category</strong><br>
          <span>&#11088;</span><%= @product.rating%>
        </ul>

      <!--
        <% if current_user.super_admin? %>
          <%= link_to "Edit this product", edit_admin_product_path(@product.id) %> |

          <% if @store %>
            <%= link_to "Back to store",  admin_products_path%><br><br>
          <% else %>
            <%= link_to "Back to all products", admin_products_path %>
          <% end %>

          <%= button_to "Destroy this product", admin_product_path(code: @product.code), method: :delete %>
        <% end %>
      -->
      </div>
</div>

<style>
  .leftx{
    position: absolute;
  }
  .rightx{
    position:absolute;
    float:right;
    margin-left: 850px;
  }
  .mybox{
    align-content: center;
    position:relative;
    top:175px;
    display:block;
    text-align: center;
  }
</style>
