config/routes.rb
Rails.application.routes.draw do
  get "payments/create"
  devise_for :users

  root "products#home"
  get "/home", to: "products#home", as: "home_user"
  get "/all_products", to: "products#all_products", as: "all_products"
  get "/record", to: "products#record", as: "record"

  resources :users do
    resources :addresses
  end

  resources :categories, param: "category_name"
  resources :products, param: "code"
  resources :stores
  resources :orders

  resources :stores do
    resources :products, param: "code"
  end

  resources :categories do
    resources :products, param: "code"
  end

  resources :products, param: "code" do
    resources :reviews
  end

  get "/cart", to: "carts#show", as: "cart"
  delete "carts/:id", to: "carts#destroy"
  post "/carts/add_to_cart", to: "carts#add_to_cart", as: "add_to_cart"
  delete "/carts/remove_from_cart/:id", to: "carts#remove_from_cart", as: "remove_from_cart"
  get "carts/empty_cart", to: "carts#empty_cart", as: "empty_cart"
  patch "carts/update_cart/:id", to: "carts#update_cart", as: "update_cart"
  get "/error", to: "carts#error", as: "error"

  post "line_items/:id/add", to: "line_items#add_quantity", as: "line_item_add"
  post "line_items/:id/reduce", to: "line_items#reduce_quantity", as: "line_item_reduce"
  post "line_items", to: "line_items#create"
  get "line_items/:id", to: "line_items#show", as: "line_item"
  delete "line_items/:id", to: "line_items#destroy"


  get "/checkout", to: "carts#checkout", as: "checkout"
  post "/place_order", to: "carts#place_order", as: "place_order"
  # post '/payments/create', to: 'payments#create', as: ""
  get "/thank_you", to: "orders#thank_you"

  namespace :admin do
    resources :users
    resources :products, param: "code"
    resources :stores
    resources :categories, param: "category_name"
    resources :orders

    resources :stores do
      resources :products, param: "code"
    end

    resources :categories do
      resources :products, param: "code"
    end
  end

  get "/admin/dashboard", to: "admin/users#dashboard", as: "admin_dashboard"
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items
  has_many :orders, through: :line_items
  has_many :reviews, dependent: :destroy, autosave: true

  belongs_to :category
  belongs_to :store

  mount_uploader :image, ImageUploader

  validates :product_name, presence: true
  validates :description, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :image, allow_blank: false, format: {
    with: %r{\.(gif|jpg|png)\Z}i,
    message: "must be a URL for GIF, JPG or PNG image."
  }
  validates :code, numericality: {only_integer: true}, presence: true, uniqueness: true, length: {is: 5, message: "Assign unique product code with 5 digits"}

  def to_param
    code
  end

  def discounted_price
    if discount
      price - (price * (discount.to_f / 100))
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:all_products, :record, :home, :show]
  before_action :set_product, only: %i[show update destroy]
  before_action :check_user_permission

  def home
    render template: "home"
  end

  def index
    @products = Product.all
    if params[:store_id]
      @products = Store.find(params[:store_id]).products
    end
    if current_user.store_admin?
      @products = Store.find(current_user.store_id).products
    end
    if params[:category_id]
      @category = Category.find(params[:category_id])
      @products = @products.where(category_id: @category.id)
    end
  end

  def show
    @store = Store.find(params[:store_id]) if params[:store_id]
    @category = Category.find(category_name: params[:category_name]) if params[:category_name]
    @product = Product.find_by(code: params[:code])
  end

  def record
    @products = Product.order(rating: :desc).paginate(page: 1, per_page: 5)
    render template: "record"
  end

  def new
    @product = Product.new
    @stores = Store.all
    @stores = Store.where(id: current_user.store_id) if current_user.store_admin?
  end

  def edit
    @product = Product.find_by(code: params[:code])
  end

  def create
    @product = Product.new(product_name: params[:product_name], price: params[:price], description: params[:description], discount: params[:discount], image: params[:image], rating: params[:rating], code: params[:code], store_id: params[:store_id], category_id: params[:category_id])
    # @product.rating = 0
    if @product.save
      redirect_to admin_products_path, notice: "Added a product successfully"
    else
      render action: "new"
    end
  end

  def update
    @product = Product.find_by(code: params[:code])
    if @product.update(product_params)
      redirect_to admin_products_path, notice: "Updated product successfully"
    else
      render action: "edit"
    end
  end

  def destroy
    @product.destroy
    redirect_to admin_products_path, notice: "Product destroyed successfully"
  end

  private

  def set_product
    @product = Product.find_by(code: params[:code])
  end

  def set_store
    @store = Store.find(params[:store_id])
  end

  def set_category
    @category = Category.find(params[:category_id])
  end

  def product_params
    params.permit(:product_name, :price, :description, :discount, :image, :rating, :code, :store_id, :category_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:all_products, :record, :home, :show]
  before_action :set_product, only: %i[show update destroy]

  def home
    render template: "home"
  end

  def index
    @products = Product.all
    @products = @products.paginate(page: params[:page], per_page: params[:per_page])
  end

  def all_products
    @products = Product.all
    @per_page = params[:per_page] if params[:per_page]
    @sort_price = params[:sort_price] if params[:sort_price]
    @products = @products.paginate(page: params[:page], per_page: params[:per_page])
    if @sort_price == "Price - low to high"
      @products = Product.order(price: :asc).paginate(page: params[:page], per_page: params[:per_page])
    elsif @sort_price == "Price - high to low"
      @products = Product.order(price: :desc).paginate(page: params[:page], per_page: params[:per_page])
    elsif @sort_price == "Relevance"
      @products = Product.paginate(page: params[:page], per_page: params[:per_page])
    elsif @sort_price == "Highest rating"
      @products = Product.order(rating: :desc).paginate(page: params[:page], per_page: params[:per_page])
    end

    @category_id = params[:category_id] if params[:category_id] && params[:category_id].present?
    @products = @products.where(category_id: @category_id) if @category_id
  end

  def show
    @store = Store.find(params[:store_id]) if params[:store_id]
    @product = Product.find_by(code: params[:code])
  end

  def record
    @products = Product.order(rating: :desc).paginate(page: 1, per_page: 5)
    render template: "record"
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:code])
  end

  def create
    @product = Product.create(product_name: params[:product_name], price: params[:price], description: params[:description], discount: params[:discount], visibility: params[:visibility], rating: params[:rating], image: params[:image], code: params[:code])
    if @product.save
      redirect_to products_path
    end
  end

  def update
    @product = Product.find(params[:code])
    @product.update(product_params)
    redirect_to products_path
  end

  def destroy
    @product = Product.find(params[:code])
    @product.destroy
    redirect_to products_path
  end

  private

  def set_product
    @product = Product.find_by(code: params[:code])
  end

  def set_store
    @store = Store.find(params[:store_id])
  end

  def set_category
    @category = Category.find(params[:category_id])
  end

  def product_params
    params.require(:product).permit(:product_name, :price, :description, :discount, :visibility, :image, :rating, :code, :store_id, :category_id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="row py-2">
 <div class= "col-lg-4 mx-auto">
    <%= form_with url: products_path do |form| %>
      <% if product.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
            <% product.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

    
      <div class="field mt-3">
        <%= form.label :product_name, style: "display: block" %>
        <%= form.text_field :product_name , autofocus: true, autocomplete: "product_name", :required =>true, class:"form-control py-2"  %>
      </div>
 
      <div class="field mt-3">
        <%= form.label :description, style: "display: block" %>
        <%= form.text_area :description, autofocus: true, autocomplete: "description", :required =>true, class:"form-control py-2"  %>
      </div>

      <div class="field mt-3">
        <%= form.label :price, style: "display: block" %>
        <%= form.number_field :price , autofocus: true, autocomplete: "price", :required =>true, class:"form-control py-2" %>
      </div>

      <div class="field mt-3">
        <%= form.label :rating, style:"display: block"%>
        <%= form.number_field :rating , step:0.01, autofocus: true, autocomplete: "rating", :required =>true, class:"form-control py-2" %>
      </div>

      <div class="field mt-3">
        <%= form.label :category, style: "display: block"  %>
        <%= select_tag "category_id", options_from_collection_for_select(Category.all, "category_name", "category_name"), autofocus: true, autocomplete: "category", :required =>true, class:"form-control py-2"  %>
      </div>
      <div class="field mt-3">
        <%= form.label :store, style: "display: block"  %>
        <%= select_tag "store_id", options_from_collection_for_select(Store.all, "store_name", "store_name"), autofocus: true, autocomplete: "store", :required =>true, class:"form-control py-2"  %>
      </div>

      <div class="field mt-3">
        <%= form.label :code, style: "display:block"%>
        <%= form.number_field :code, autofocus: true, autocomplete: "code", :required =>true, class:"form-control py-2"  %>
      </div>

      <div class="field mt-3">
        <%= form.label :discount, style: "display: block" %>
        <%= form.number_field :discount, autofocus: true, autocomplete: "discount", :required =>true, class:"form-control py-2"  %>
      </div>

      <div class="field mt-3">
        <%= form.label :visibility, style: "display: block" %>
        <%= form.check_box :visibility %>
      </div>
    
      <div class="field mt-3">
        <%= form.label :image, style: "display: block" %>
        <%= form.file_field :image, autofocus: true, :required =>true, class:"form-control py-2"  %>
        <!--
        <% if @product.image %>
          <%= form.check_box :remove_image%>
        Remove image
        <%end%>
        -->
      </div>

      <% if @product.image.present?%>
        <div>
          <%= image_tag @product.image%>
        </div>
      <% end %>
  
      <div class="actions mt-4 mb-5" >
        <%= form.submit "Create", data: {turbo:false}, class:"form-control py-2 btn btn-dark fw-bold shadow"%>
      </div>
    <% end %>
</div>

<div>
  <%= link_to "Back to products", admin_products_path %>
</div>

app/views/products/_product.html.erb
<div class="col-md-4">
  <div class="product-box" id="product-box">
    <a><%= link_to image_tag(product.image.url , class:"product-index"), product_path(code: product.code) %></a>
        <ul>
          <strong class="product-name"><%= product.product_name%></strong><br>by <strong><%= product.store.store_name%></strong><br>
          <!--<div style="font-weight:bold;color:red;"><%= product.discount %>% Off</div>-->
              <% if product.discounted_price%>
                <%= content_tag :p, product.price, style: "text-decoration: line-through;color: gray; margin-bottom: 0px" %>
                <strong>Rs.<%= product.discounted_price%></strong><br>
              <% else %>
                <strong>Rs.<%= product.price%></strong><br>
              <% end%>
              <% unless product.rating %>
                <%= render plain: "-Be the first to review-" %>
              <% else %>
                <span>&#11088;</span><%=product.rating %>
              <% end %>
              
              <%= form_with url: add_to_cart_path, method: :post do |form|%>
                <%= form.hidden_field :product_id, value: product.id %>
                <%= form.label :qty%>
                <%= form.select :quantity, [1,2,3,4,5,6,7,8,9] %>
                <%= form.submit "Add to Cart", class:"form-control py-2 btn btn-success fw-bold shadow" %>
              <% end %>
        </ul>
  </div>
</div>

<style>
.striked-price{

color: red;
}
</style>

app/views/products/_product_box.html.erb
<div class="col-md-4">
  <div class="product-box" id="product-box">
    <a><%= link_to image_tag(product.image.url , class:"product-index"), product_path(code: product.code) %></a>
        <ul>
          <strong class="product-name"><%= product.product_name%></strong><br>by <strong><%= product.store.store_name%></strong><br>
              Rs.<%= product.price%><br>
              <span>&#11088;</span><%= product.rating%><br>
              
              <%= form_with url: add_to_cart_path, method: :post do |form|%>
                <%= form.hidden_field :product_id, value: product.id %>
                <%= form.label :qty%>
                <%= form.select :quantity, [1,2,3,4,5,6,7,8,9] %>
                <%= form.submit "Add to Cart", class:"form-control py-2 btn btn-success fw-bold shadow" %>
              <% end %>
        </ul>
  </div>
</div>

app/views/products/all_products.html.erb
<div id="design-outline">
  <%= form_with url: all_products_path ,id: 'pages_filter' ,class: 'filter d-flex', method: :get, remote: true do |form| %>
      
    <%= form.select :per_page,[1,2,3,4,5,10,20,30], {:prompt => true, :selected => @per_page || 10}, {class: 'form-control py-1 m-20', style: "width:50px;"}  %><br><br>

    <%= form.label :sort_by %>
    <%= form.select :sort_price,["Relevance","Price - low to high","Price - high to low", "Highest rating"], {:prompt => true, :selected => @sort_price || "Relevance"}, {class: 'form-control py-1 m-20', style: "width:200px;"} %>

    <%= form.label :categories %>
    <%= select_tag :category_id, options_from_collection_for_select(Category.all, "id", "category_name", :selected => @category_id), include_blank: "All", class: 'form-control py-1 m-20', style: "width:200px;"%>
    <%= form.submit "Filter"%>
  <% end %>
  <div class="apple_pagination" >
    <%= page_entries_info @products %><br>
    <%= will_paginate @products, :container => false %>
  </div>
</div>
 
<div class="row" style="margin-bottom:60px;">
  <% @products.each do |product|%>
      <%= render "product", product: product %>
  <%end%>
</div>

<%= javascript_include_tag "show"%>
<%= javascript_include_tag "Changefun"%>

<script>
function handleChange(filter){
  console.log(filter)
  $(document).ready(function(){
    var review = $('#review');
    var form = $(`#${filter}`);
    console.log(form)
    var actionUrl = form.attr('action');
    console.log(actionUrl)
    $.ajax({
      url: `${actionUrl}.json`,
        type: 'GET',
        data: form.serialize()
      })
    .done( function(data){
      console.log(data)
      })
      .fail( function(error){
        alert("somthing went wrong! try again");
        });
    });
}
</script>


app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", product_path%> |
  <%= link_to "Back to products", products_path %>
</div>

<!---- fo show this product store_product_path(product.store,product) or product-->

app/views/products/index.html.erb
<div class="text-center">
  <h1>Products</h1><%= link_to "Add products to this store" ,new_product_path %>
</div>


<div id="design-outline">

<div class="apple_pagination">

  
    <%= page_entries_info @products %>
  
  
    <%= will_paginate @products, :container => false %><br>

    <%= form_with url: all_products_path , method: :get do |form| %>
      <%= form.number_field :per_page %>
      <%= form.submit %>
    <% end %> 
</div>

<div class="pagenum1">
  <%= form_with url: all_products_path , method: :get do |form| %>
    <%= form.label :sort_by %>
    <%= form.select :sort_price, ["Relevance","Price - low to high","Price - high to low"] %>
    <%= form.submit %>
  <% end %><br>


</div>

<div>
<%= form_with url: all_products_path, method: :get do |form|%>
   <span id="checkbox"> <% Product::CATEGORIES.each do |key|%>
             <%= form.check_box :categories, {multiple: true}, key, nil%>
             <%= form.label key%>
    <%end%></span>
    <%= form.submit "Filter by"%>
<% end %>
</div>

</div>

  <div class="row">
    <% @products.each do |product|%>
        <div class="col-md-4" onclick="show(this)">

          <div class="product-box">
              <%=image_tag product.image.url, class:"product-index" if product.image?%>
                <ul>
                      <strong><%= product.product_name%></strong><br>by <strong><%= product.store.store_name%></strong><br>
                      Rs.<%= product.price%><br>
                      <span>&#11088;</span><%= product.rating%><br>
                      
                      | <%= link_to "", product_path(code: product.code)%> |
                      <%= button_to "Add to cart", line_items_path(code: product.code), class: "btn btn-success" %>

                      
                   </li>
                </ul>
          </div>

          
        </div>
    <%end%>
  </div>

<%= javascript_include_tag "show"%>




app/views/products/new.html.erb
<h1 class="text-center">New product</h1>

<%= render "form", product: @product %>

<br>

<div class="text-center">
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<div class="mybox">
      <div class="leftx">
        <% if @product.image?%>
          <%= image_tag @product.image.url, class:"product-show"%>
          <%else %>
          <%= render plain: "OK" %>
        <% end %><br>
      </div>


      <div class="rightx" >
        <ul>
          <strong><%= @product.product_name%></strong><br>by <strong><%= @product.store.store_name%></strong><br>
          <% if @product.discounted_price%>
            <%= content_tag :p, @product.price, style: "text-decoration: line-through;color: gray; margin-bottom: 0px" %>
            <strong>Rs.<%= @product.discounted_price%></strong><br>
          <% else %>
            <strong>Rs.<%= @product.price%></strong><br>
          <% end%>
          <strong>Description:</strong> <%= @product.description%><br>
          <strong><%= @product.category.category_name%>'s Category</strong><br>
          <span>&#11088;</span><%= @product.rating%>
        </ul>

        <div class="btn-group mr-2" role="group" >
          <%= form_with url: add_to_cart_path, method: :post do |form|%>
            <%= form.hidden_field :product_id, value: @product.id %>
            <%= button_tag "-", type: 'button', onclick: "decrement()", class: 'btn btn-default'%>
            <%= form.number_field :quantity, min: 0, max: 10, value:1 %>
            <%= button_tag "+", type: 'button', onclick: "increment()", class: 'btn btn-default'%><br>
            <%= form.submit 'Add to Cart', class: "btn btn-success" %>
          <% end %>
        </div> 
        <div class="review-box" style="margin-bottom: 100px">
          <h3>Reviews</h3>
          <% @product.reviews.each do |review| %>
            <strong>Rating:</strong><%= review.rating %><span>&#11088;</span><br>
            <strong></strong><%= review.comment %>
            by<strong><%= review.user.name %></strong><br>
          <% end %>
          <%= link_to "Write my review", new_product_review_path(product_code: @product.code)%>
        </div>



      </div>
</div>

<script>
function increment() {
  // debugger;
  document.getElementById('quantity').stepUp();
}
function decrement() {
  document.getElementById('quantity').stepDown();
}
</script>
